import { type NextPage } from 'next';
import Head from 'next/head';

import Header from '~/components/Header';
import Content from '~/components/Content';
import { Container } from '@mantine/core';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Notetaker-trpc</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container fluid p={0} m={0}>
        <Header />
        <Content />
      </Container>
    </>
  );
};

export default Home;
